### ISSUE TITLE
[Administrator] Request force-return

### ISSUE THREAD

**Issue by anandimous** [anandimous/DAM#5]
**User Stories**
As an Administrator, I want to:
- request force return so that if the due date is passed, the client is fined
- request force return so that if the item has any issues, the client is informed

**Acceptance Test**
Given that I am an Administrator, when I:
- request force-return an item, it should send an email to the clients notifying about the relevant action

**Comment by lawzeem** [comment]
We are not doing this for for this sprint. Since we decided not to add email verification and authorization as UB faculty and students use different providers for emails. This issue can be revisited in the future if it is thought to be necessary. Managers will already have access to Clients emails through their reservations and can request force return by individually emailing them for now.
